version: "3.1"

services:
  pingaccess:
    image: pingidentity/pingaccess
    command: wait-for pingfederate:9031 -t 420 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
      - SERVER_PROFILE_PATH=Solution-BaselineCustomer/pingaccess
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet-dmz

  pingfederate:
    image: pingidentity/pingfederate
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
      - SERVER_PROFILE_PATH=Solution-BaselineCustomer/pingfederate
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
          # aliases: 
          #   - pingfederate-admin

  pingdirectory:
    image: pingidentity/pingdirectory
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
      - SERVER_PROFILE_PATH=Solution-BaselineCustomer/pingdirectory
      - USER_BASE_DN=dc=anycompany,dc=co
      - VERBOSE=true
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal

  pingdatagovernance:
    image: pingidentity/pingdatagovernance
    env_file:
      - ~/.pingidentity/devops
    command: wait-for pingfederate:9031 -t 300 -- entrypoint.sh start-server
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
      - SERVER_PROFILE_PATH=Solution-BaselineCustomer/pingdatagovernance
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 2443:443
    networks:
      - pingnet-internal

  pingdatasync:
    image: pingidentity/pingdatasync
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-solution-stacks.git
      - SERVER_PROFILE_PATH=Solution-BaselineCustomer/pingdatasync
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 3636:636
      - 3443:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole
    env_file:
      - ~/.pingidentity/devops
    ports:
      - 8080:8080
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
